version: '3'
services:
  mymongo:
    image: mongo:latest
    container_name: "mymongo"
    ports:
      - 27017:27017
  demo-mongo:
    image: mongodbexample-0.0.1
    container_name: demo-mongo
    ports:
      - 8080:8080
    links:
      - mymongo